"""Repository Intelligence Core V1.

Pure, deterministic, transport-neutral advisory intelligence facade.
"""
from __future__ import annotations

from .models import Disposition

from .contracts import (
    CLAIM_CEILING,
    CI_EVIDENCE_CLAIM_CEILING,
    REPOSITORY_FACTS_CLAIM_CEILING,
    REPOSITORY_QUERY_CLAIM_CEILING,
    TERMINAL_FAILURE_STATUSES,
    SUPPORTED_TERMINAL_FAILURES,
    is_terminal_failure_status,
    CIFailureFingerprint,
    CIFailureIntelligenceReportV1,
    CIFailureTriageStatus,
    CandidateMatchClass,
    ChangeImpactReportV1,
    ExternalIntelligenceAutomationEnvelopeV1,
    ExternalIntelligenceDecision,
    CrossPROverlapResult,
    EvidenceCompleteness,
    FusedCandidateV1,
    NormalizedCheckEvidence,
    RankedCandidateV1,
    ReadinessClassification,
    RepositoryFactEvidenceV1,
    RepositoryFactKind,
    RepositoryFactStatus,
    RepositoryFactV1,
    RepositoryIntelligencePolicyV1,
    RepositoryIntelligenceReportV1,
    RepositoryQueryEvidenceReportV1,
    RepositoryQueryResolution,
    RetrieverIdentityV1,
    RetrieverRunV1,
    RevisionIdentity,
    StructuredFactsReportV1,
)
from .facts import analyze_structured_facts, verify_structured_facts_report
from .impact import analyze_change_impact, verify_change_impact_report
from .cfi import analyze_ci_failure_intelligence, verify_ci_failure_intelligence_report
from .eia import plan_external_intelligence_automation, verify_external_intelligence_automation_envelope
from .retrieval import analyze_repository_query, verify_repository_query_evidence
from .core import (
    analyze_cross_pr_overlap,
    build_repository_intelligence_report,
    classify_readiness,
    fingerprint_ci_failures,
    revision_identity,
    verify_ci_failure_evidence,
    verify_repository_intelligence_report,
)

__all__ = [
    "CLAIM_CEILING",
    "CI_EVIDENCE_CLAIM_CEILING",
    "REPOSITORY_FACTS_CLAIM_CEILING",
    "REPOSITORY_QUERY_CLAIM_CEILING",
    "TERMINAL_FAILURE_STATUSES",
    "SUPPORTED_TERMINAL_FAILURES",
    "is_terminal_failure_status",
    "Disposition",
    "EvidenceCompleteness",
    "RepositoryIntelligencePolicyV1",
    "RevisionIdentity",
    "ReadinessClassification",
    "CrossPROverlapResult",
    "NormalizedCheckEvidence",
    "CIFailureFingerprint",
    "CIFailureTriageStatus",
    "CIFailureIntelligenceReportV1",
    "CandidateMatchClass",
    "ChangeImpactReportV1",
    "ExternalIntelligenceDecision",
    "ExternalIntelligenceAutomationEnvelopeV1",
    "RepositoryIntelligenceReportV1",
    "RepositoryFactKind",
    "RepositoryFactStatus",
    "RepositoryFactEvidenceV1",
    "RepositoryFactV1",
    "StructuredFactsReportV1",
    "RetrieverIdentityV1",
    "RetrieverRunV1",
    "RankedCandidateV1",
    "FusedCandidateV1",
    "RepositoryQueryEvidenceReportV1",
    "RepositoryQueryResolution",
    "revision_identity",
    "classify_readiness",
    "analyze_cross_pr_overlap",
    "fingerprint_ci_failures",
    "verify_ci_failure_evidence",
    "analyze_change_impact",
    "verify_change_impact_report",
    "analyze_ci_failure_intelligence",
    "verify_ci_failure_intelligence_report",
    "plan_external_intelligence_automation",
    "verify_external_intelligence_automation_envelope",
    "analyze_structured_facts",
    "verify_structured_facts_report",
    "analyze_repository_query",
    "verify_repository_query_evidence",
    "build_repository_intelligence_report",
    "verify_repository_intelligence_report",
]
